# The workflow to run the tests
name: Testing

# Controls when the workflow will run
on: [pull_request]

jobs:
  test:
    # The matrix of OS and Node.js versions
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      # Use Node.js LTS version
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: "Install dependencies and build"
        run: npm ci && npm run build

      - name: "Run Tests"
        run: npm run test
